name: "Release AUR"

on:
  release:
    types:
      - published

env:
  PKGNAME: uoj-data-converter

jobs:
  aur:
    name: "Update AUR"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ouuan'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"

      - name: Update PKGBUILD
        run: |
          wget -c https://github.com/${{ github.repository }}/archive/${{ steps.get-version.outputs.version }}.tar.gz
          sha256sum=$(shasum -a 256 *.tar.gz | cut -d ' ' -f 1)
          sed -i "s/@VERSION@/${{ steps.get-version.outputs.version }}/g" aur/release/PKGBUILD aur/release/.SRCINFO
          sed -i "s/SKIP/${sha256sum}/" aur/release/PKGBUILD aur/release/.SRCINFO
          mv aur/release "$PKGNAME"

      - name: Check PKGBUILD
        uses: 2m/arch-pkgbuild-builder@master
        with:
          target: pkgbuild
          pkgname: ${{ env.PKGNAME }}
          debug: true

      - name: Check .SRCINFO
        uses: 2m/arch-pkgbuild-builder@master
        with:
          target: srcinfo
          pkgname: ${{ env.PKGNAME }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Clone AUR and update
        run: |
          git clone ssh://aur@aur.archlinux.org/${PKGNAME}.git ../aur
          cp ${PKGNAME}/PKGBUILD ${PKGNAME}/.SRCINFO ../aur
          cd ../aur
          git config user.name "Yufan You"
          git config user.email "ouuansteve@gmail.com"
          git add -A
          git diff-index @ --exit-code --quiet || git commit -m "Update from GitHub Actions: ${{ steps.get-version.outputs.version }}

          https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          git push
